/**
 * @file    vfs.hpp
 * @brief   The path floor: one mount table over concept-checked backends.
 *
 * A backend is any type satisfying FileSystem — a plain class with nine
 * ordinary methods, compile-time checked, no table to hand-write, no
 * cast-back dance. mount() type-erases such a backend once, mechanically,
 * into one FsOps generated by EraseFs<F>, the same pair-shape the tick
 * service uses one floor down: captureless forwarders plus a context
 * pointer. The mount table then maps path prefixes to erased backends,
 * longest component-boundary prefix first, and resolve() hands back the
 * winning backend with the remainder of the path — everything past the
 * mount point, no leading slash, empty meaning the mount root itself.
 * Consumers never learn a backend's name; ramfs today, ext2 one station
 * later, behind one face.
 *
 * @author  Charliechen114514
 * @date    2026-10-07
 * @version 0.1
 * @since   0.1.0
 * @ingroup kernel_fs
 * @copyright Copyright (c) 2026
 */

#pragma once

#include <concepts>
#include <cstdint>
#include <string_view>

#include "cinux/container/slot_table.hpp"
#include "cinux/memory.hpp"
#include "cinux/result.hpp"
#include "kernel/fs/fs_config.hpp"

namespace cinux::fs {

/**
 * @brief   What a node is: a plain file or a directory.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
enum class InodeType : std::uint8_t {
    kFile,       ///< A byte sequence.
    kDirectory,  ///< A tree of names.
};

/**
 * @brief   An opaque handle to one node inside some backend.
 * @note    The backend fills every field when it hands the handle out:
 *          opaque points at the backend's own node, the rest is metadata
 *          callers can read without another call. Only the backend that
 *          minted a handle may interpret its opaque field. A borrowed
 *          handle must be retained before it can survive an unlink.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
struct FsNode {
    void*         opaque;  ///< Backend-private node pointer.
    InodeType     type;    ///< File or directory.
    unsigned long ino;     ///< Backend-assigned inode number.
    unsigned long size;    ///< File bytes; zero for directories.
};

/**
 * @brief   One directory entry, name plus what it is.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
struct FsDirent {
    char      name[kFsNameMax];  ///< NUL-terminated entry name.
    InodeType type;              ///< File or directory.
};

/**
 * @brief   What a file-system backend must offer, checked at compile time.
 * @tparam  Fs   The backend type being checked.
 * @note    Paths arrive without a leading slash, relative to the mount
 *          point; the empty path is the mount root itself. A backend
 *          keeps its own nodes; read_dir treats the index as the entry
 *          ordinal, mirroring how an open directory's offset doubles as
 *          a cursor. Requirements grow the day a consumer needs them.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
template <typename Fs>
concept FileSystem = requires(Fs& backend, std::string_view path, std::string_view name,
                              FsNode node, unsigned long offset, void* sink, const void* source,
                              unsigned long count, FsDirent& entry) {
    { backend.lookup(path) } -> std::same_as<base::Result<FsNode>>;
    { backend.make_file(path) } -> std::same_as<base::Result<FsNode>>;
    { backend.make_dir(path) } -> std::same_as<base::Result<FsNode>>;
    { backend.unlink(path) } -> std::same_as<base::Result<void>>;
    { backend.read(node, offset, sink, count) } -> std::same_as<base::Result<unsigned long>>;
    { backend.write(node, offset, source, count) } -> std::same_as<base::Result<unsigned long>>;
    { backend.read_dir(node, offset, entry) } -> std::same_as<base::Result<bool>>;
    { backend.retain(node) } -> std::same_as<void>;
    { backend.release(node) } -> std::same_as<void>;
};

/**
 * @brief   The erased backend face: node operations and reference hooks.
 * @note    Generated, never hand-written: EraseFs<Fs> builds the whole
 *          struct from a concept-checked type, so a new backend adds
 *          zero boilerplate and the cast back to the real type lives in
 *          exactly one generated place per backend. retain/release are
 *          non-failing ownership hooks for live nodes; contract violations
 *          terminate rather than return a recoverable error.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
struct FsOps {
    /// Finds a node by mount-relative path.
    base::Result<FsNode> (*lookup)(void* self, std::string_view path);
    /// Creates a file at a mount-relative path.
    base::Result<FsNode> (*make_file)(void* self, std::string_view path);
    /// Creates a directory at a mount-relative path.
    base::Result<FsNode> (*make_dir)(void* self, std::string_view path);
    /// Removes a file or an empty directory.
    base::Result<void> (*unlink)(void* self, std::string_view path);
    /// Reads up to count bytes at offset into sink.
    base::Result<unsigned long> (*read)(void* self, FsNode node, unsigned long offset, void* sink,
                                        unsigned long count);
    /// Writes count bytes from source at offset, growing as needed.
    base::Result<unsigned long> (*write)(void* self, FsNode node, unsigned long offset,
                                         const void* source, unsigned long count);
    /// Fills entry with the index-th child; false means index is past the end.
    base::Result<bool> (*read_dir)(void* self, FsNode node, unsigned long index, FsDirent& entry);
    /// Pins a borrowed node for an open descriptor.
    void (*retain)(void* self, FsNode node);
    /// Drops a descriptor's pin, reclaiming an unlinked node at the last release.
    void (*release)(void* self, FsNode node);
};

/**
 * @brief         Builds the erased face for one concept-checked backend.
 * @tparam        Fs   Backend type satisfying FileSystem.
 * @return        The complete FsOps for that type.
 * @note          Every forwarder is captureless, so each decays to a
 *                plain function pointer; the backend pointer rides along
 *                as the first argument at call time, never stored inside.
 * @since         0.1.0
 * @ingroup       kernel_fs
 */
template <FileSystem Fs>
[[nodiscard]] constexpr FsOps EraseFs() {
    return {
        [](void* self, std::string_view path) { return static_cast<Fs*>(self)->lookup(path); },
        [](void* self, std::string_view path) { return static_cast<Fs*>(self)->make_file(path); },
        [](void* self, std::string_view path) { return static_cast<Fs*>(self)->make_dir(path); },
        [](void* self, std::string_view path) { return static_cast<Fs*>(self)->unlink(path); },
        [](void* self, FsNode node, unsigned long offset, void* sink, unsigned long count) {
            return static_cast<Fs*>(self)->read(node, offset, sink, count);
        },
        [](void* self, FsNode node, unsigned long offset, const void* source, unsigned long count) {
            return static_cast<Fs*>(self)->write(node, offset, source, count);
        },
        [](void* self, FsNode node, unsigned long index, FsDirent& entry) {
            return static_cast<Fs*>(self)->read_dir(node, index, entry);
        },
        [](void* self, FsNode node) { static_cast<Fs*>(self)->retain(node); },
        [](void* self, FsNode node) { static_cast<Fs*>(self)->release(node); },
    };
}

/**
 * @brief   A resolved path: which backend serves it, and what is left.
 * @note    rest carries no leading slash; empty rest addresses the mount
 *          root. Callers forward rest to the backend through ops.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
struct FsView {
    const FsOps*     ops;   ///< The winning backend's erased face.
    void*            self;  ///< The winning backend instance.
    std::string_view rest;  ///< Path past the mount point.
};

/**
 * @brief   The mount table: path prefixes to backends, nothing more.
 * @note    An instance class on purpose — a test world builds its own
 *          table, the kernel builds the one it wires. Fixed slots keep
 *          the object constant-initializable, so it can sit in a
 *          freestanding singleton later without a constructor story.
 * @since   0.1.0
 * @ingroup kernel_fs
 */
class Vfs {
public:
    Vfs() = default;

    Vfs(const Vfs&)            = delete;
    Vfs& operator=(const Vfs&) = delete;

    /**
     * @brief         Places a backend at a path prefix.
     *
     * @param[in]     prefix   Mount point; must start with '/', carry no
     *                        trailing '/' unless it is exactly "/", and
     *                        stay under kFsPathMax.
     * @param[in,out] backend   Backend instance; its lifetime must cover
     *                        every later use of the table.
     * @return        Success, or kInvalidArgument (shape), kAlreadyExists
     *                (same prefix mounted twice), kOutOfMemory (table full).
     * @note          Type erasure happens exactly here, once per mount.
     * @since         0.1.0
     * @ingroup       kernel_fs
     */
    template <FileSystem Fs>
    base::Result<void> mount(std::string_view prefix, Fs& backend) {
        if (prefix.empty() || prefix.front() != '/' || prefix.size() >= kFsPathMax) {
            return base::KernelError::kInvalidArgument;
        }
        if (prefix.size() > 1 && prefix.back() == '/') {
            return base::KernelError::kInvalidArgument;
        }

        const auto kExisting = slots_.find_if([prefix](const Slot& slot) {
            return std::string_view(slot.prefix, slot.prefix_len) == prefix;
        });
        if (kExisting != kMountMax) {
            return base::KernelError::kAlreadyExists;
        }
        static constexpr FsOps kErased = EraseFs<Fs>();
        Slot                   slot{.ops = &kErased, .self = &backend, .prefix_len = prefix.size()};
        base::CopyBytes(slot.prefix, prefix.data(), prefix.size());
        if (slots_.insert(slot) == kMountMax) {
            return base::KernelError::kOutOfMemory;
        }
        return {};
    }

    /**
     * @brief         Maps a full path onto the deepest mount covering it.
     *
     * @param[in]     path   Absolute path to resolve.
     * @return        The winning backend plus the mount-relative rest,
     *                or kInvalidArgument (not absolute), kNotFound
     *                (no mount covers the path).
     * @note          Prefixes match only on component boundaries: mount
     *                "/tmp" serves "/tmp" and "/tmp/build" but never
     *                "/tmpx". Among covering mounts the longest prefix
     *                wins.
     * @since         0.1.0
     * @ingroup       kernel_fs
     */
    [[nodiscard]] base::Result<FsView> resolve(std::string_view path) const;

private:
    /**
     * @brief   One table row: a prefix and its erased backend.
     * @since   0.1.0
     * @ingroup kernel_fs
     */
    struct Slot {
        const FsOps*  ops                = nullptr;
        void*         self               = nullptr;
        unsigned long prefix_len         = 0;
        char          prefix[kFsPathMax] = {};
    };

    base::container::SlotTable<Slot, kMountMax> slots_;
};

}  // namespace cinux::fs
