/**
 * @file    isr.hpp
 * @brief   The shared face between ISR stubs and the exception reporter.
 *
 * Stubs are generated by the compiler from the x86 interrupt attribute —
 * no macro arrays, no hand-written assembly. Each template instantiation
 * bakes its vector number into the call it makes, and the two signature
 * shapes (with and without a CPU-pushed error code) funnel into the one
 * reporter below with a uniform frame pointer.
 *
 * @author  Charliechen114514
 * @date    2026-10-02
 * @version 0.1
 * @since   0.1.0
 * @ingroup kernel_arch
 * @copyright Copyright (c) 2026
 */

#pragma once

namespace cinux::arch::isr {

struct [[gnu::packed]] InterruptFrame {
    unsigned long long rip;
    unsigned long long cs;
    unsigned long long rflags;
    unsigned long long rsp;
    unsigned long long ss;
};

/**
 * @brief         Report one fault: named vector plus the frame that caused it.
 * @param[in]     vector      CPU exception number, 0..31.
 * @param[in]     frame       The frame the stub received, rip onward.
 * @param[in]     error_code  CPU-pushed code, 0 for no-code exceptions.
 * @return        None.
 * @note          Prints the dump and parks the machine; resumable faults
 *                arrive with the kernel-side test framework, not here.
 * @since         0.1.0
 * @ingroup       kernel_arch
 */
void ReportFault(unsigned long long vector, const InterruptFrame& frame,
                 unsigned long long error_code);

/**
 * @brief         Arm all 32 CPU exception vectors with attribute stubs.
 * @return        None.
 * @note          Vectors 8, 10-14, 17, 21, 29 and 30 take the error-code
 *                signature; the rest take the bare one. Every stub here
 *                lands before lidt makes the table live.
 * @since         0.1.0
 * @ingroup       kernel_arch
 */
void InstallExceptionStubs();

}  // namespace cinux::arch::isr
