/**
 * @file    isr.hpp
 * @brief   The shared face between ISR stubs and the exception reporter.
 *
 * Stubs are generated by the compiler from the x86 interrupt attribute —
 * no macro arrays, no hand-written assembly. Each template instantiation
 * bakes its vector number into the call it makes, and the two signature
 * shapes (with and without a CPU-pushed error code) funnel into the one
 * reporter below with a uniform frame pointer.
 *
 * @author  Charliechen114514
 * @date    2026-10-02
 * @version 0.1
 * @since   0.1.0
 * @ingroup kernel_arch
 * @copyright Copyright (c) 2026
 */

#pragma once

namespace cinux::arch::isr {

struct [[gnu::packed]] InterruptFrame {
    unsigned long long rip;
    unsigned long long cs;
    unsigned long long rflags;
    unsigned long long rsp;
    unsigned long long ss;
};

/**
 * @brief         Report one fault: named vector plus the frame that caused it.
 * @param[in]     vector      CPU exception number, 0..31.
 * @param[in,out] frame       The frame the stub received; rip moves forward
 *                            when an armed recovery consumes this fault.
 * @param[in]     error_code  CPU-pushed code, 0 for no-code exceptions.
 * @return        None.
 * @note          An armed-and-matching fault is repaired and returned
 *                through iret; every other fault prints the dump and
 *                parks the machine.
 * @since         0.1.0
 * @ingroup       kernel_arch
 */
void ReportFault(unsigned long long vector, InterruptFrame& frame, unsigned long long error_code);

/**
 * @brief         Arm one fault as expected and resumable.
 * @param[in]     vector       The exception number to intercept.
 * @param[in]     skip_bytes   Instruction length to step rip past on resume.
 * @return        true when armed; false when a previous arm is pending.
 * @note          The resumable-fault probe, a miniature of the exception
 *                tables real kernels use for speculative access: when the
 *                armed vector fires, the reporter advances rip by
 *                skip_bytes and iret-returns instead of dumping. Any other
 *                fault, or one nobody armed, behaves as always.
 * @since         0.2.0
 * @ingroup       kernel_arch
 */
bool ArmRecoverableFault(unsigned long long vector, unsigned long long skip_bytes);

/**
 * @brief         Take the vector of the last recovered fault, if any.
 * @return        The recovered vector, or 256 — one past all real CPU
 *                vectors — when the arm never fired.
 * @note          Reading consumes the record; a second call without a new
 *                recovery answers 256, the no-fault sentinel.
 * @since         0.2.0
 * @ingroup       kernel_arch
 */
unsigned long long TakeRecoveredVector();

/**
 * @brief         Arm all 32 CPU exception vectors with attribute stubs.
 * @return        None.
 * @note          Vectors 8, 10-14, 17, 21, 29 and 30 take the error-code
 *                signature; the rest take the bare one. Every stub here
 *                lands before lidt makes the table live.
 * @since         0.1.0
 * @ingroup       kernel_arch
 */
void InstallExceptionStubs();

}  // namespace cinux::arch::isr
