/**
 * @file    block_device_concept.hpp
 * @brief   The block-device face: sector words, a compile-time contract,
 *          and its erased form.
 *
 * A block device is any type satisfying BlockDevice — a plain class with
 * five ordinary methods, checked at compile time, no inheritance, no
 * hand-written table. adopt() type-erases such a device once, into one
 * BlockOps generated by EraseBlockDevice, the same pair-shape the tick
 * service and the path floor use: captureless forwarders plus a context
 * pointer. Consumers hold a BlockPort and never learn which device sits
 * behind it; the AHCI drive today, NVMe and virtio at a later station.
 *
 * @author  Charliechen114514
 * @date    2026-10-08
 * @version 0.1
 * @since   0.1.0
 * @ingroup kernel_driver
 * @copyright Copyright (c) 2026
 */

#pragma once

#include <concepts>
#include <cstdint>

namespace cinux::driver {

/**
 * @brief   A sector address, as its own word.
 * @note    The number's meaning lives in the type: forty-eight bits of
 *          sector position on the addressed device, never a bare count
 *          or byte offset.
 * @since   0.1.0
 * @ingroup kernel_driver
 */
struct Lba {
    std::uint64_t value;  ///< Sector position, zero-based.
};

/**
 * @brief   How many sectors one request spans.
 * @since   0.1.0
 * @ingroup kernel_driver
 */
struct BlockSpan {
    std::uint16_t value;  ///< Sector count, one upward.
};

/**
 * @brief   What a block device must offer, checked at compile time.
 * @tparam  Dev   The device type being checked.
 * @note    Blocks are the device's own transfer unit — on this machine
 *          today, the 512-byte sector. read_blocks and write_blocks
 *          block the caller until the device finished; flush orders
 *          writes behind it before any later one. Requirements grow
 *          the day a consumer needs them.
 * @since   0.1.0
 * @ingroup kernel_driver
 */
template <typename Dev>
concept BlockDevice = requires(Dev& device, Lba first, BlockSpan span, std::uint8_t* sink,
                               const std::uint8_t* source) {
    { device.read_blocks(first, span, sink) } -> std::same_as<bool>;
    { device.write_blocks(first, span, source) } -> std::same_as<bool>;
    { device.block_count() } -> std::same_as<std::uint64_t>;
    { device.block_size() } -> std::same_as<unsigned long>;
    { device.flush() } -> std::same_as<bool>;
};

/**
 * @brief   The erased device face: five plain entry points.
 * @note    Generated, never hand-written: EraseBlockDevice builds the
 *          whole struct from a concept-checked type, so a new device
 *          adds zero boilerplate and the cast back to the real type
 *          lives in exactly one generated place per device.
 * @since   0.1.0
 * @ingroup kernel_driver
 */
struct BlockOps {
    /// Reads span blocks at first into sink.
    bool (*read_blocks)(void* self, Lba first, BlockSpan span, std::uint8_t* sink);
    /// Writes span blocks at first from source.
    bool (*write_blocks)(void* self, Lba first, BlockSpan span, const std::uint8_t* source);
    /// How many blocks the device addresses.
    std::uint64_t (*block_count)(void* self);
    /// The device's transfer unit in bytes.
    unsigned long (*block_size)(void* self);
    /// Orders writes behind this call before any later one.
    bool (*flush)(void* self);
};

/**
 * @brief         Builds the erased face for one concept-checked device.
 * @tparam        Dev   Device type satisfying BlockDevice.
 * @return        The complete BlockOps for that type.
 * @note          Every forwarder is captureless, so each decays to a
 *                plain function pointer; the device pointer rides along
 *                as the first argument at call time, never stored inside.
 * @since         0.1.0
 * @ingroup       kernel_driver
 */
template <BlockDevice Dev>
[[nodiscard]] constexpr BlockOps EraseBlockDevice() {
    return {
        [](void* self, Lba first, BlockSpan span, std::uint8_t* sink) {
            return static_cast<Dev*>(self)->read_blocks(first, span, sink);
        },
        [](void* self, Lba first, BlockSpan span, const std::uint8_t* source) {
            return static_cast<Dev*>(self)->write_blocks(first, span, source);
        },
        [](void* self) { return static_cast<Dev*>(self)->block_count(); },
        [](void* self) { return static_cast<Dev*>(self)->block_size(); },
        [](void* self) { return static_cast<Dev*>(self)->flush(); },
    };
}

/**
 * @brief   One block device behind the face, ready to call.
 * @note    adopt() erases exactly once per device; the device's lifetime
 *          must cover every later call through the port. An unadopted
 *          port answers nothing: every entry stays null and the
 *          forwarders refuse the call.
 * @since   0.1.0
 * @ingroup kernel_driver
 */
class BlockPort {
public:
    BlockPort() = default;

    /**
     * @brief         Seats one concept-checked device behind this port.
     *
     * @param[in,out] device  The device instance taking the seat.
     * @return        None
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    template <BlockDevice Dev>
    void adopt(Dev& device) {
        static constexpr BlockOps kErased = EraseBlockDevice<Dev>();
        ops_                              = &kErased;
        self_                             = &device;
    }

    /**
     * @brief         Reads span blocks at first into sink.
     *
     * @param[in]     first  First block to read.
     * @param[in]     span   Blocks to read.
     * @param[out]    sink   Memory the blocks land in.
     * @return        True when the device moved every block.
     * @note          Refuses an unadopted port with false.
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    [[nodiscard]] bool read_blocks(Lba first, BlockSpan span, std::uint8_t* sink) const {
        return ops_ != nullptr && ops_->read_blocks(self_, first, span, sink);
    }

    /**
     * @brief         Writes span blocks at first from source.
     *
     * @param[in]     first   First block to write.
     * @param[in]     span    Blocks to write.
     * @param[in]     source  Memory the blocks leave from.
     * @return        True when the device took every block.
     * @note          Refuses an unadopted port with false.
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    [[nodiscard]] bool write_blocks(Lba first, BlockSpan span, const std::uint8_t* source) const {
        return ops_ != nullptr && ops_->write_blocks(self_, first, span, source);
    }

    /**
     * @brief         How many blocks the seated device addresses.
     *
     * @return        Block count, zero for an unadopted port.
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    [[nodiscard]] std::uint64_t block_count() const {
        return ops_ != nullptr ? ops_->block_count(self_) : 0;
    }

    /**
     * @brief         The seated device's transfer unit in bytes.
     *
     * @return        Block size, zero for an unadopted port.
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    [[nodiscard]] unsigned long block_size() const {
        return ops_ != nullptr ? ops_->block_size(self_) : 0;
    }

    /**
     * @brief         Orders seated writes before any later one.
     *
     * @return        True when the device flushed, false for an
     *                      unadopted port or a device refusal.
     * @since         0.1.0
     * @ingroup       kernel_driver
     */
    [[nodiscard]] bool flush() const { return ops_ != nullptr && ops_->flush(self_); }

private:
    const BlockOps* ops_  = nullptr;
    void*           self_ = nullptr;
};

}  // namespace cinux::driver
